Repository danarbello/astro-portfolio, pull requests merged in 2025-03, with the labels that each got.

#14 Add prototype redirects to astro.config.mjs
  astro.config.mjs
  src/pages/case-studies/aerospace.astro
Labels: Priority: Critical, Engineering

#18 GH-13 • Update Readme
  README.md
Labels: Priority: Meh, Engineering

#19 GH-6 • Create Metadata Frontmatter Logic
  src/components/Head.astro
  src/layouts/Basic.astro
  src/pages/case-studies/aerospace.astro
  src/pages/case-studies/draper.astro
  src/pages/case-studies/imprivata.astro
  src/pages/case-studies/sunpower.astro
  src/pages/case-studies/swedish-news.astro
Labels: Priority: Medium, Content, Engineering

#25 GH-24 • Resolve Prototype Redirects Loop
  astro.config.mjs
  public/prototypes/aerospace/index.html
  public/prototypes/apollo/index.html
  public/prototypes/apollo2/index.html
  public/prototypes/apollo3/index.html
  public/prototypes/cariq/index.html
  public/prototypes/draper/index.html
  public/prototypes/energy-portal/index.html
  public/prototypes/literacypro-ui/index.html
  public/prototypes/literacypro-ux/index.html
  public/prototypes/sunpower-extra/index.html
  public/prototypes/sunpower-extra/stylesheet.html
  public/prototypes/sunpower-poc/ddp3.html
  public/prototypes/sunpower-poc/index.html
  public/prototypes/sunpower/index.html
  public/prototypes/sunpower/stylesheet.html
  public/prototypes/sunpower/sws205.html
  public/prototypes/texaslawhelp/index.html
  public/prototypes/william-sonoma/index.html
Labels: Priority: Critical, Engineering

#30 Update Resume PDF
  public/Dan Arbello - Resume.pdf
Labels: Content
